### ISSUE TITLE
Native LMS API won't build on Ubuntu 22.04.

### ISSUE THREAD

**Issue by 9600** [myriadrf/srsRAN#1]
The `native_lime_22.04` branch won't build on Ubuntu 22.04. See below. It may have been that the warnings were always there, but the compiler on Ubuntu 22.04 defaults to being more strict and now build fails. In any case, the warnings need resolving.

//

[ 69%] Linking CXX executable rlc_am_nr_pdu_test
/home/ciran1/srsRAN-LMS/lib/src/phy/rf/rf_lime_imp.c: In function ‘rf_lime_open_multi’:
/home/ciran1/srsRAN-LMS/lib/src/phy/rf/rf_lime_imp.c:621:9: error: ‘LMS_WriteCustomBoardParam’ reading 16 bytes from a region of size 1 [-Werror=stringop-overread]
  621 |     if (LMS_WriteCustomBoardParam(handler->device, 0, tcxo_val, "") != 0) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ciran1/srsRAN-LMS/lib/src/phy/rf/rf_lime_imp.c:621:9: note: referencing argument 4 of type ‘const char *’
In file included from /home/ciran1/srsRAN-LMS/lib/src/phy/rf/rf_lime_imp.c:23:
/usr/local/include/lime/LimeSuite.h:901:26: note: in a call to function ‘LMS_WriteCustomBoardParam’
  901 | API_EXPORT int CALL_CONV LMS_WriteCustomBoardParam(lms_device_t *device,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~
[ 69%] Built target asn1_utils_test
Consolidate compiler generated dependencies of target rlc_stress_test
[ 69%] Linking CXX executable rlc_stress_test
[ 70%] Built target rlc_am_nr_pdu_test
Consolidate compiler generated dependencies of target rlc_um_nr_pdu_test
[ 70%] Linking CXX executable rlc_um_nr_pdu_test
cc1: all warnings being treated as errors
make[2]: *** [lib/src/phy/rf/CMakeFiles/srsran_rf_lime.dir/build.make:76: lib/src/phy/rf/CMakeFiles/srsran_rf_lime.dir/rf_lime_imp.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6208: lib/src/phy/rf/CMakeFiles/srsran_rf_lime.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Built target rlc_um_nr_pdu_test
[ 71%] Built target rlc_stress_test
[ 71%] Linking CXX shared library libsrsran_rf_soapy.so
[ 71%] Built target srsran_rf_soapy
make: *** [Makefile:166: all] Error 2
ciran1@ciran1:~/srsRAN-LMS/build$
